name = "zonix-cloud"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
[env.production]
name = "zonix-cloud-prod"
workers_dev = false
routes = [
  { pattern = "zonix.me/*", zone_name = "zonix.me" }
]

[build]
command = "pnpm run build"
cwd = "."
watch_paths = ["app/**/*", "components/**/*", "lib/**/*", "public/**/*"]

[build.upload]
format = "modules"
main = "./.next/server/index.js"
